### ISSUE TITLE
Duplicate form fields in admin for user profiles

### ISSUE THREAD

**Issue by stephenmcd** [stephenmcd/mezzanine#1449]
As discussed here:

https://groups.google.com/forum/#!topic/mezzanine-users/3QmiqfNZjUM

**Comment by molokov** [comment]
It's probably an issue in mezzanine/accounts/templates/admin/profile_inline.html from what I can tell. 

Possibly:

     <div class="items">
          {% for inline_admin_form in inline_admin_formset %}
          <div class="{% if inline_admin_form.original or inline_admin_form.show_url %} has_original{% endif %}">

needs something similar to https://github.com/stephenmcd/grappelli-safe/commit/21ba4fac50441cd6825585da9380fe42569ac2db ?

**Comment by molokov** [comment]
Ok, I think I have it worked out - First, we should add
    {% if forloop.last %} empty-form{% endif %}

within the class part of the div above (as per the grapelli-safe fix) and then add this to admin/global.css:

    fieldset.profile .items .empty-form {
        display: none;
    }

I can set up a PR if you like.

**Comment by stephenmcd** [comment]
Sure, please do.

**Comment by stephenmcd** [comment]
Fixed in #1450

**Comment by stephenmcd** [comment]
At this point in time, this change ends up hiding all profile fields, and when I back out this change, only one set of fields are shown - given that, I'll revert it.

**Comment by molokov** [comment]
With this reverted, I'm still seeing profile fields duplicated in admin, the second set being empty. It's really annoying. My project uses AUTH_PROFILE_MODULE to define the profile fields in my own profile class. I'll override the templates locally to fix this, but I really wish there's a solution that works for everyone.

**Comment by AlexHill** [comment]
I still see this too.

I think the difference comes down to whether or not a profile object already exists. If it doesn't, the only form generated will be the empty form, which will be hidden and so you'll see nothing.

To get around this, we just need ``min_num = 1`` added to ``ProfileInline``. See #1517

**Comment by AlexHill** [comment]
I've moved the CSS fix to grappelli - see stephenmcd/grappelli-safe#65. Without grappelli, vanilla Django provides this CSS rule, so it doesn't need to be included in Mezzanine.
