### ISSUE TITLE
Insert/Edit link is dead

### ISSUE THREAD

**Issue by mani098** [stephenmcd/mezzanine#1537]
Insert/edit link is not working. It seems to be dead
![image](https://cloud.githubusercontent.com/assets/7437058/13009557/0201d87a-d1c3-11e5-90d7-3597d09e42f1.png)

**Comment by molokov** [comment]
Fixed in https://github.com/stephenmcd/mezzanine/commit/94d57294bcc1e934fdd723546be7ea15bb9dcd1a
See also https://github.com/stephenmcd/mezzanine/pull/1516

**Comment by ghilbrae** [comment]
Hi,

I've tried applying the fix on my local mezzanine/core/managers.py but it still does not work and the debug shows the following:

`Internal Server Error: /displayable_links.js
Traceback (most recent call last):
  File "/home/user/Projects/virtualenvs/myproject-mezzanine/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/Projects/virtualenvs/myproject-mezzanine/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/Projects/virtualenvs/myproject-mezzanine/lib/python3.4/site-packages/mezzanine/core/views.py", line 192, in displayable_links_js
    for url, obj in Displayable.objects.url_map(for_user=request.user).items():
  File "/home/user/Projects/virtualenvs/myproject-mezzanine/lib/python3.4/site-packages/mezzanine/core/managers.py", line 374, in url_map
    for item in (model.objects.published(for_user=for_user)
AttributeError: 'SearchableManager' object has no attribute 'published'
[20/Apr/2016 11:15:44] "GET /displayable_links.js HTTP/1.1" 500 19654
`
Is there something else I might be missing? This is happening in the blog Posts that come with Mezzanine. I don't know if it might have something to do with the fact that I have a couple of classes in the app I am developing that inherit from Displayable. I followed the documentation to create them, so i added to their models

```
objects = SearchableManager()
search_fields = ("title", "description", "keywords")
```
and defined the SEARCH_MODEL_CHOICES.

What I've tested so far is commenting this two lines and also the SEARCH_MODEL_CHOICES in my settings.py. When I do this the error I get is:

`
Internal Server Error: /displayable_links.js
Traceback (most recent call last):
  File "/home/user/Projects/virtualenvs/myproject-mezzanine/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/Projects/virtualenvs/myproject-mezzanine/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/Projects/virtualenvs/myproject-mezzanine/lib/python3.4/site-packages/mezzanine/core/views.py", line 200, in displayable_links_js
    sorted_links = sorted(links, key=lambda link: (link[0], link[1]['value']))
TypeError: unorderable types: str() < NoneType()
`

Many thanks!

**Comment by lmregus** [comment]
I also applied the fix and still not working.

**Comment by darkos** [comment]
I am commenting here because I think it is the same issue:
I tried to insert/edit link and nothing was happening.
(tried in both python 2 and 3)

Errors thrown:

**In python 2:**
(deeper below is python 3 errors as well)
python 2.7.12
Django==1.9.11
Mezzanine==4.1.0

File "/home/darko/desk/programs/pyenvs/2.7.12/venv2712/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/darko/desk/programs/pyenvs/2.7.12/venv2712/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/darko/desk/programs/pyenvs/2.7.12/venv2712/lib/python2.7/site-packages/mezzanine/core/views.py", line 192, in displayable_links_js
    for url, obj in Displayable.objects.url_map(for_user=request.user).items():
  File "/home/darko/desk/programs/pyenvs/2.7.12/venv2712/lib/python2.7/site-packages/mezzanine/core/managers.py", line 366, in url_map
    home = self.model(title=_("Home"))
  File "/home/darko/desk/programs/pyenvs/2.7.12/venv2712/lib/python2.7/site-packages/django/db/models/base.py", line 416, in __init__
    val = field.get_default()
  File "/home/darko/desk/programs/pyenvs/2.7.12/venv2712/lib/python2.7/site-packages/django/db/models/fields/related.py", line 905, in get_default
    if isinstance(field_default, self.remote_field.model):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types


**In python 3**
python 3.5.2
Django==1.9.11
Mezzanine==4.1.0

Internal Server Error: /displayable_links.js
Traceback (most recent call last):
  File "/home/darko/desk/programs/pyenvs/3.5.2/venv352/lib/python3.5/site-packages/django/db/models/base.py", line 409, in __init__
    rel_obj = kwargs.pop(field.name)
KeyError: 'site'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/darko/desk/programs/pyenvs/3.5.2/venv352/lib/python3.5/site-packages/django/db/models/base.py", line 414, in __init__
    val = kwargs.pop(field.attname)
KeyError: 'site_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/darko/desk/programs/pyenvs/3.5.2/venv352/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/darko/desk/programs/pyenvs/3.5.2/venv352/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/darko/desk/programs/pyenvs/3.5.2/venv352/lib/python3.5/site-packages/mezzanine/core/views.py", line 192, in displayable_links_js
    for url, obj in Displayable.objects.url_map(for_user=request.user).items():
  File "/home/darko/desk/programs/pyenvs/3.5.2/venv352/lib/python3.5/site-packages/mezzanine/core/managers.py", line 366, in url_map
    home = self.model(title=_("Home"))
  File "/home/darko/desk/programs/pyenvs/3.5.2/venv352/lib/python3.5/site-packages/django/db/models/base.py", line 416, in __init__
    val = field.get_default()
  File "/home/darko/desk/programs/pyenvs/3.5.2/venv352/lib/python3.5/site-packages/django/db/models/fields/related.py", line 905, in get_default
    if isinstance(field_default, self.remote_field.model):
TypeError: isinstance() arg 2 must be a type or tuple of types

**Comment by antuanjoseff** [comment]
I've being dealing with the same issue. 
When click on the "Add link" button on the tinymce editor, I get and error 404 /displayable_links.js/ not found.
So, I edited the file : admin\js\mezza\tinymce_setup.js and change the link_list property, for something more explicit.
I changed:
link_list: '/displayable_links.js'
for:
link_list: 'route/to/my/app/displayable_links.js'

Where 'route/to/my/app' is defined in settings.py file as 
BASE_URL = '/route/to/my/app/'

Hope it helps someone out there.
