### ISSUE TITLE
Website: Free Themes url 404

### ISSUE THREAD

**Issue by COLABORATI** [stephenmcd/mezzanine#1623]
The [Free Themes](http://thecodinghouse.in/themes/) Link on the main website is a 404.

Question: How can you and I do url checks with mezzanine? is there some functionality that checks all urls in content and removes it or sends an email if 404? 

Thanks!

**Comment by stephenmcd** [comment]
That's already fixed in the repo. You should post your other question to the mailing list.

**Comment by COLABORATI** [comment]
The error is still alive, maybe I was not clear.

This is about the main website for mezzanine. The link to free themes on the **main project website** is still 404. If you understood that and do not care, then I believe you are very much underestimating how much this hurts your project. I bet a very big percentage of people that look for the first time on the mezzanine project page and would like to inform themselves are leaving when they see that such an important link is 404 on the main project page. I did that, too, because it signals multiple things that might be very wrong, but do very bad propaganda for your work: 
* free themes are not available for this cms
* this is an abandoned project as there is a dead link on the project start page (no-go for every serious project)
* the author / team is not interested in users and this is just a small private project
* the cms has no possibility to check for dead links
 
I am not writing this to annoy you - I just think that django is very nice and after a second look also mezzanine looks interesting, but it hurts very much when possible customers see a catastrophic 404 on the main project site.  Just to make clear, that this was not about some code in the repo.

**Comment by stephenmcd** [comment]
> Just to make clear, that this was not about some code in the repo.

But it literally is part of this repo - here's the fix I was referring to: d6ee2811b2308710c1f83c661b359b6c0252b55a

We'll close issues here once they're resolved in the repo, regardless of where that fix eventually needs to make its way to, be it PyPI for the source code, or something such as this case that controls content on the project site.

**Comment by COLABORATI** [comment]
OK, I now better understand the context, sorry!
